// PocketCode — Catrobat-style mobile scratch: project import/export, media packs, touch interactions.
// Generated by the Counted Repo Factory (seeds/seeds.yaml). Deterministic by construction.
// Layout: docs/REPO_STANDARD.md — core logic in src/lib/, public API in src/index.ts.

import { seededRandom } from "./lib/rng";
import { ProjectIO, MediaPacks, TouchInteractions } from "./lib/modules";

export const SPEC = "Catrobat-style mobile scratch: project import/export, media packs, touch interactions.";
export const MODULES = [{ id: "ProjectIO", name: "PocketCode :: ProjectIO" }, { id: "MediaPacks", name: "PocketCode :: MediaPacks" }, { id: "TouchInteractions", name: "PocketCode :: TouchInteractions" }];
export { seededRandom };
export class Registry {
  private items = new Map<string, string>();
  constructor(seed = 42) {
    const rng = seededRandom(seed);
    for (const mod of MODULES) {
      const n = 1 + Math.floor(rng() * 4);
      for (let i = 0; i < n; i++) {
        this.items.set(mod.id + "-" + i, mod.name);
      }
    }
  }
  count(): number { return this.items.size; }
  get(id: string): string | undefined { return this.items.get(id); }
  ids(): string[] { return [...this.items.keys()]; }
  lookup(name: string): string[] {
    return this.ids().filter((id) => this.items.get(id) === name);
  }
}
